### ISSUE TITLE
HTML meta description for each page

### ISSUE THREAD

**Issue by Mecanik** [razonyang/hugo-theme-bootstrap#877]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

It seems that you cannot set a description for custom page and instead the description from params is being used across all pages. 

This is big issue from an SEO point of view and more.

### Steps to reproduce

I tried to set description after title inside custom pages but it's not being recognised.

### Expected behavior

description should be used if specified in the meta header.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

v1.0.0-beta2.0.20230127171944-4e82cc64584f

### What version of Hugo are you using?

v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended

**Comment by Mecanik** [comment]
It seems that if the page is rich format (+++) the description is read, but otherwiser (---) not...

**Comment by Mecanik** [comment]
Is it possible to add support for plain page type as well? Because my HTML does not work in rich format for some reason.

**Comment by razonyang** [comment]
Could you please provide a sample of your custom page to reproduce and test this issue.

**Comment by Mecanik** [comment]
> Could you please provide a sample of your custom page to reproduce and test this issue.

Yes, so the pages are like this:

---
title: Home
type: landing
sidebar: false
---

If you add the description is not read.

**Comment by Mecanik** [comment]
Thank you.
